name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[cpu,docs]"

    - name: Generate API Documentation
      run: |
        sphinx-apidoc -o docs/source/ login_field_detector/

    - name: Build Documentation
      working-directory: docs
      run: |
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: docs/build/html
