name: Upload Model to Hugging Face

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  upload-to-hf:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Activate Virtual Environment
        run: |
          source ~/.virtualenvs/LoginFieldDetector/bin/activate

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train the model
        run: |
          PYTHONLOGGING=INFO python -m login_field_detector.field_detector


      - name: Upload Model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import Repository
          repo = Repository(local_dir='model', repo_id='byvictorrr/html-login-field-detector', token='${{ secrets.HF_TOKEN }}')
          repo.push_to_hub()
          "
