name: Upload Model to Hugging Face

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  upload-to-hf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface_hub

      - name: Train the model
        run: |
          python -m login_field_detector.field_detector


      - name: Upload Model to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c "
          from huggingface_hub import Repository
          repo = Repository(local_dir='model', repo_id='byvictorrr/html-login-field-detector', token='${{ secrets.HF_TOKEN }}')
          repo.push_to_hub()
          "
